HospitalManagementSystemMvc.Mvc/Controllers/Billing/BillingController.cs
using HospitalManagementSystemMvc.Models.Billing;
using HospitalManagementSystemMvc.Services.Billing;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagementSystemMvc.Mvc.Controllers;
public class BillingController : Controller
{
    private readonly IBillingService _BillingService;
    public BillingController(IBillingService BillingService)
    {
        _BillingService = BillingService;
    }

    public async Task<IActionResult> Index()
    {
        List<BillingIndexViewModel> Billings = await _BillingService.GetAllBillingAsync();

        return View(Billings);
    }

    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(BillingCreateViewModel model)
    {
        if (!ModelState.IsValid)
        {
            TempData["ErrorMsg"] = "Model State is invalid.";
            return View(model);
        }

        if (await _BillingService.CreateBillingAsync(model) is false)
        {
            TempData["ErrorMsg"] = "Unable to save to the database. Please try again later.";
            return View(model);
        }

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Details(int id)
    {
        if (id == 0)
        {
            return RedirectToAction(nameof(Index));
        }

        var Billing = await _BillingService.GetBillingByIdAsync(id);

        if (Billing is null)
        {
            return RedirectToAction(nameof(Index));
        }

        return View(Billing);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        if (id == 0)
        {
            return RedirectToAction(nameof(Index));
        }

        var bill = await _BillingService.GetBillingByIdAsync(id);

        BillingEditViewModel model = new()
        {
            BillingId = bill.BillingId,
            PatientId = bill.PatientId,
            Amount = bill.Amount,
            DateOfBilling = bill.DateOfBilling
        };

        if (bill is null)
        {
            return RedirectToAction(nameof(Index));
        }

        return View(model);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, BillingEditViewModel model)
    {
        var Billing = await _BillingService.EditBillingByIdAsync(id, model);
        if (Billing == false)
        {
            return NotFound();
        }


        return RedirectToAction(nameof(Index));


        // TempData["ErrorMsg"] = "Unable to save to the database. Please try again later.";
        // return View(model);
    }
    public async Task<IActionResult> Delete(int id)
    {
        var entity = await _BillingService.DeleteBillingByIdAsync(id);

        if (entity == null)
        {
            TempData["ErrorMsg"] = $"Billing #{id} does not exist";
            return RedirectToAction(nameof(Index));
        }

        return RedirectToAction(nameof(Index));
    }


}

HospitalManagementSystemMvc.Mvc/Views/Billing/Create.cshtml
@model HospitalManagementSystemMvc.Models.Billing.BillingCreateViewModel
@{
    ViewData["Title"] = "Create Billing";
}

@if (TempData["ErrorMsg"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>ERROR:</strong> @TempData["ErrorMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<form asp-action="Create" method="post" class="row g-3">
    <div class="col-md-6">
        <label asp-for="PatientId" class="form-label"> PatientId</label>
        <input asp-for="PatientId" class="form-control">
        <span asp-validation-for="PatientId" class="text-danger"></span>
    </div>
    <div class="col-md-6">
        <label asp-for="Amount" class="form-label">Amount</label>
        <input asp-for="Amount" class="form-control">
        <span asp-validation-for="Amount" class="text-danger"></span>
    </div>
    <div class="col-md-6">
        <label asp-for="DateOfBilling" class="form-label"></label>
        <input asp-for="DateOfBilling" class="form-control">
        <span asp-validation-for="DateOfBilling" class="text-danger"></span>
    </div>
    <div class="col d-flex justify-content-between align-items-baseline">
        <a asp-action="Index">Back to List</a>
        <input type="submit" value="Create" class="btn btn-primary">
    </div>
</form>

HospitalManagementSystemMvc.Mvc/Views/Billing/Details.cshtml
@model HospitalManagementSystemMvc.Models.Billing.BillingDetailViewModel
@{
    string title = $"Billing {Model.BillingId}";
    ViewData["Title"] = title;
}

<div class="d-flex justify-content-between align-items-center mb-2">
    <h1>@title</h1>
    <a asp-action="Edit" asp-route-id="@Model.BillingId" class="btn btn-light">Edit</a>
</div>

<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.BillingId)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.BillingId)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.PatientId)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.PatientId)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Amount)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Amount)
    </dd>
</dl>

@* <component type="typeof(int)" render-mode="ServerPrerendered" param-transactions="Model.BillingId" /> *@

<div>
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

HospitalManagementSystemMvc.Mvc/Views/Billing/Edit.cshtml
@model HospitalManagementSystemMvc.Models.Billing.BillingEditViewModel
@{
    string title = $"Edit {Model.BillingId}";
    ViewData["Title"] = title;
}

<h1>@title</h1>
@if (TempData["ErrorMsg"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>ERROR:</strong> @TempData["ErrorMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<form asp-action="Edit" class="row g-3">
    <input asp-for="Amount" hidden>
    <div class="col-md-6">
        <label asp-for="BillingId" class="form-label"></label>
        <input asp-for="BillingId" class="form-control">
        <span asp-validation-for="BillingId" class="text-danger"></span>
    </div>
    <div class="col-md-6">
        <label asp-for="PatientId" class="form-label"></label>
        <input asp-for="PatientId" class="form-control">
        <span asp-validation-for="PatientId" class="text-danger"></span>
    </div>
    <div class="col-md-6">
        <label asp-for="DateOfBilling" class="form-label"></label>
        <input asp-for="DateOfBilling" class="form-control">
        <span asp-validation-for="DateOfBilling" class="text-danger"></span>
    </div>
    <div class="col d-flex justify-content-between align-items-baseline">
        <a asp-action="Index">Back to List</a>
        <input type="submit" value="Update" class="btn btn-primary">
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

HospitalManagementSystemMvc.Mvc/Views/Billing/Index.cshtml
@model List<HospitalManagementSystemMvc.Models.Billing.BillingIndexViewModel>
@{
    ViewData["Title"] = "Billing Index";
}

<div class="d-flex flex-wrap justify-content-between align-items-baseline">
    <h1>Billing</h1>
    <a asp-controller="Billing" asp-action="Create" class="btn btn-sm btn-success">Create a Billing</a>
</div>

<table class="table table-striped border">
    <thead>
        <tr>
            <th>BillingId</th>
            <th>PatientId</th>
            <th>Amount</th>
            <th>DateOfBilling</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var Billing in  Model)
        {
            <tr>
                <td>@Billing.BillingId</td>
                <td>@Billing.PatientId</td>
                <td>@Billing.Amount</td>
                <td>@Billing.DateOfBilling</td>
                <td>
                    <a asp-action="Details" asp-route-id="@Billing.BillingId" class="btn btn-sm btn-primary">Details</a>
                    <a asp-action="Edit" asp-route-id="@Billing.BillingId" class="btn btn-sm btn-primary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@Billing.BillingId" class="btn btn-sm btn-primary">Delete</a>
                </td>                
            </tr>
        }
    </tbody>
</table>