HospitalManagementSystemMvc.Mvc/Controllers/AppointmentController.cs
using HospitalManagementSystemMvc.Models.Appointment;
using HospitalManagementSystemMvc.Services.Appointment;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagementSystemMvc.Mvc.Controllers;
public class   AppointmentController : Controller
{
    private readonly IAppointmentService _AppointmentService;
    public AppointmentController(IAppointmentService AppointmentService)
    {
        _AppointmentService = AppointmentService;
    }

    public async Task<IActionResult> Index()
    {
        List<AppointmentIndexViewModel> Appointments = await _AppointmentService.GetAllAppointmentAsync();

        return View(Appointments);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(AppointmentCreateViewModel model)
    {
        if (!ModelState.IsValid)
        {
            TempData["ErrorMsg"] = "Model State is invalid.";
            return View(model);
        }

        if (await _AppointmentService.CreateAppointmentAsync(model) is false)
        {
            TempData["ErrorMsg"] = "Unable to save to the database. Please try again later.";
            return View(model);
        }

        return RedirectToAction(nameof(Index));
    }

    // GET: Appointment/details/{id}
    public async Task<IActionResult> Details(int id)
    {
        if (id == 0)
        {
            return RedirectToAction(nameof(Index));
        }

        var Appointment= await _AppointmentService.GetAppointmentByIdAsync(  id);

        if (Appointment is null)
        {
            return RedirectToAction(nameof(Index));
        }

        return View(Appointment);
    }

    // GET: Appointment/edit/{id}
    public async Task<IActionResult> Edit(int id)
    {
        if (id ==0)
        {
            return RedirectToAction(nameof(Index));
        }
        
        var Appointment = await _AppointmentService.GetAppointmentByIdAsync(id);

        AppointmentEditViewModel model = new()
        {
            Id = Appointment.Id,
            PatientId = Appointment.PatientId,
            DoctorId = Appointment.DoctorId,
            DateCreated = Appointment.DateCreated          
        };

        if (model is null)
        {
            return RedirectToAction(nameof(Index));
        }
        return View(model);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, AppointmentEditViewModel model)
    {
        var Appointment= await _AppointmentService.EditAppointmentByIdAsync(id, model);
        if (Appointment== false)
        {
            return NotFound();
        }

        if (Appointment!= false)
        {
            return RedirectToAction(nameof(Index));
        }

        TempData["ErrorMsg"] = "Unable to save to the database. Please try again later.";
        return View(model);
    }

    // GET: Appointment/delete/{id}
    public async Task<IActionResult> Delete(int id)
    {
        var entity = await _AppointmentService.DeleteAppointmentByIdAsync( id);

        if (entity == null)
        {
            TempData["ErrorMsg"] = $"Doctor #{id} does not exist";
            return RedirectToAction(nameof(Index));
        }

        return RedirectToAction(nameof(Index));
    }
}

HospitalManagementSystemMvc.Mvc/Controllers/DepartmentController.cs
using System.ComponentModel.DataAnnotations;
using HospitalManagementSystemMvc.Models.Department;
using HospitalManagementSystemMvc.Services.Department;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagementSystemMvc.Mvc.Controllers;
public class DepartmentController : Controller
{
    private readonly IDepartmentService _DepartmentService;
    public DepartmentController(IDepartmentService DepartmentService)
    {
        _DepartmentService = DepartmentService;
    }
     public async Task<IActionResult> Index()
    {
        List<DepartmentIndexViewModel> Departments = await _DepartmentService.GetAllDepartmentAsync();

        return View(Departments);
    }

    public IActionResult Create()
    {
        return View();
    }

      [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(DepartmentCreateViewModel model)
    {
        if (!ModelState.IsValid)
        {
            TempData["ErrorMsg"] = "Model State is invalid.";
            return View(model);
        }

        if (await _DepartmentService.CreateDepartmentAsync(model) is false)
        {
            TempData["ErrorMsg"] = "Unable to save to the database. Please try again later.";
            return View(model);
        }

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Details(int id)
    {
        if (id == 0)
        {
            return RedirectToAction(nameof(Index));
        }

        var Department= await _DepartmentService.GetDepartmentByIdAsync(  id);

        if (Department is null)
        {
            return RedirectToAction(nameof(Index));
        }

        return View(Department);
    }

    // GET: Department/edit/{id}
    public async Task<IActionResult> Edit(int id)
    {
        if (id == 0)
        {
            return RedirectToAction(nameof(Index));
        }
        
        var department = await _DepartmentService.GetDepartmentByIdAsync(id);

       DepartmentEditViewModel model = new()
        {
            DepartmentId = department.DepartmentId,
            Name = department.Name,
            Email = department.Email,
            Address = department.Address
        };
        if (department is null)
        {
            return RedirectToAction(nameof(Index));
        }
        return View(model);
    }

    // [HttpGet]
    // public IActionResult Edit()
    // {
    //     return View();
    // }

      [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, DepartmentEditViewModel model)
    {
        var Department= await _DepartmentService.EditDepartmentByIdAsync(id, model);
        if (Department== false)
        {
            return NotFound();
        }

        if (Department!= false)
        {
            return RedirectToAction(nameof(Index));
        }

        TempData["ErrorMsg"] = "Unable to save to the database. Please try again later.";
        return View(model);
    }

    public async Task<IActionResult> Delete(int id)
    {
        var entity = await _DepartmentService.DeleteDepartmentByIdAsync( id);

        if (entity == null)
        {
            TempData["ErrorMsg"] = $"Doctor #{id} does not exist";
            return RedirectToAction(nameof(Index));
        }

        return RedirectToAction(nameof(Index));
    }

}

HospitalManagementSystemMvc.Mvc/Controllers/DoctorController.cs
using HospitalManagementSystemMvc.Models.Doctor;
using HospitalManagementSystemMvc.Services.Doctor;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagementSystemMvc.Mvc.Controllers;
public class   DoctorController : Controller
{
    private readonly IDoctorService _DoctorService;
    public DoctorController(IDoctorService DoctorService)
    {
        _DoctorService = DoctorService;
    }

    public async Task<IActionResult> Index()
    {
        List<DoctorIndexViewModel> doctors = await _DoctorService.GetAllDoctorsAsync();

        return View(doctors);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(DoctorCreateViewModel model)
    {
        if (!ModelState.IsValid)
        {
            TempData["ErrorMsg"] = "Model State is invalid.";
            return View(model);
        }

        if (await _DoctorService.CreateDoctorAsync(model) is false)
        {
            TempData["ErrorMsg"] = "Unable to save to the database. Please try again later.";
            return View(model);
        }

        return RedirectToAction(nameof(Index));
    }

    // GET: Doctor/details/{id}
    public async Task<IActionResult> Details(int? id)
    {
        if (id is null)
        {
            return RedirectToAction(nameof(Index));
        }

        var Doctor= await _DoctorService.GetDoctorByIdAsync((int)id);

        if (Doctor is null)
        {
            return RedirectToAction(nameof(Index));
        }

        return View(Doctor);
    }

    // GET: Doctor/edit/{id}
    public async Task<IActionResult> Edit(int id)
    {
        if (id == 0)
        {
            return RedirectToAction(nameof(Index));
        }
        
        var doctor = await _DoctorService.GetDoctorByIdAsync(id);

        DoctorEditViewModel model = new()
        {
            Id = doctor.Id,
            FirstName = doctor.FirstName,
            LastName = doctor.LastName,
            Email = doctor.Email,
            Address = doctor.Address
        };
        if (doctor is null)
        {
            return RedirectToAction(nameof(Index));
        }
        return View(model);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, DoctorEditViewModel model)
    {
        var Doctor= await _DoctorService.EditDoctorByIdAsync(id, model);
        if (Doctor == false)
        {
            return NotFound();
        }

        if (Doctor != false)
        {
            return RedirectToAction(nameof(Index));
        }

        TempData["ErrorMsg"] = "Unable to save to the database. Please try again later.";
        return View(model);
    }

    // GET: Doctor/delete/{id}
    public async Task<IActionResult> Delete(int id)
    {
        var entity = await _DoctorService.DeleteDoctorByIdAsync( id);

        if (entity == null)
        {
            TempData["ErrorMsg"] = $"Doctor #{id} does not exist";
            return RedirectToAction(nameof(Index));
        }

        return RedirectToAction(nameof(Index));
    }
}

HospitalManagementSystemMvc.Mvc/Controllers/PatientController.cs
using HospitalManagementSystemMvc.Services.Patient;
using HospitalManagementSystemMvc.Models.Patient;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagementSystemMvc.Mvc.Controllers;
public class PatientController : Controller
{
    private readonly IPatientService _patientService;
    public PatientController(IPatientService patientService)
    {
        _patientService = patientService;
    }

    public async Task<IActionResult> Index()
    {
        List<PatientIndexViewModel> patient = await _patientService.GetAllPatientsAsync();

        return View(patient);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(PatientCreateViewModel model)
    {
        if (!ModelState.IsValid)
        {
            TempData["ErrorMsg"] = "Model State is invalid.";
            return View(model);
        }

        if (await _patientService.CreatePatientAsync(model) is false)
        {
            TempData["ErrorMsg"] = "Unable to save to the database. Please try again later.";
            return View(model);
        }

        return RedirectToAction(nameof(Index));
    }

    // GET: patient/details/{id}
    public async Task<IActionResult> Details(int? id)
    {
        if (id is null)
        {
            return RedirectToAction(nameof(Index));
        }

        var patient = await _patientService.GetPatientByIdAsync(id);

        if (patient is null)
        {
            return RedirectToAction(nameof(Index));
        }

        return View(patient);
    }

    // GET: patient/edit/{id}
    public async Task<IActionResult> Edit(int? id)
    {
        if (id is null)
        {
            return RedirectToAction(nameof(Index));
        }
        
        var patient = await _patientService.GetEditPatientByIdAsync(id);

        if (patient is null)
        {
            return RedirectToAction(nameof(Index));
        }
        return View(patient);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, PatientEditViewModel model)
    {
        var patient= await _patientService.EditPatientByIdAsync(id, model);
        if (patient == false)
        {
            return NotFound();
        }

        if (patient != false)
        {
            return RedirectToAction(nameof(Index));
        }

        TempData["ErrorMsg"] = "Unable to save to the database. Please try again later.";
        return View(model);
    }

    // GET: patient/delete/{id}
    public async Task<IActionResult> Delete(int id)
    {
        var entity = await _patientService.DeletePatientAsync( id);

        if (entity == false)
        {
            TempData["ErrorMsg"] = $"Patient #{id} does not exist";
            return RedirectToAction(nameof(Index));
        }

        return RedirectToAction(nameof(Index));
    }
}

HospitalManagementSystemMvc.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalManagementSystemMvc.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HospitalManagementSystemMvc.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HospitalManagementSystemMvc.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="Index">Patient</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Billing" asp-action="Index">Billing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Doctor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="Index">Appointment</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HospitalManagementSystemMvc.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>